=== regecz/CNGDZ3WebXML/CNGDZ3_feleves_feladat/XMLSchemaCNGDZ3.xsd
<!-- XMLSchemaNeptunkod.xsd -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Gyökérelem -->
    <xs:element name="Adatbazis">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Tipusok" type="TipusokType"/>
                <xs:element name="Termekek" type="TermekekType"/>
                <xs:element name="Rendelesek" type="RendelesekType"/>
                <xs:element name="Dolgozok" type="DolgozokType"/>
                <xs:element name="Vasarlok" type="VasarlokType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Típusok -->
    <!-- A Típusok gyűjtő elemének típusa -->
    <xs:complexType name="TipusokType">
        <xs:sequence>
            <xs:element name="Tipus" type="TipusType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Egy Típus elemet leíró típus -->
    <xs:complexType name="TipusType">
        <xs:attribute name="TipKod" type="xs:int" use="required"/>
        <xs:attribute name="TNev" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Termékek -->
    <!-- A Termékek gyűjtő elemének típusa -->
    <xs:complexType name="TermekekType">
        <xs:sequence>
            <xs:element name="Termek" type="TermekType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Egy Termék elemet leíró típus -->
    <xs:complexType name="TermekType">
        <xs:attribute name="TerKod" type="xs:int" use="required"/>
        <xs:attribute name="TerNev" type="xs:string" use="required"/>
        <xs:attribute name="TermekAr" type="xs:decimal" use="required"/>
        <xs:attribute name="TipKod" type="xs:int" use="required"/>
    </xs:complexType>

    <!-- Rendelések -->
    <!-- A Rendelesek gyűjtő elemének típusa -->
    <xs:complexType name="RendelesekType">
        <xs:sequence>
            <xs:element name="Rendeles" type="RendelesType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Egy Rendelés elemet leíró típus -->
    <xs:complexType name="RendelesType">
        <xs:sequence>
            <xs:element name="Kiszallitas" type="KiszallitasType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="RSzam" type="xs:string" use="required"/>
        <xs:attribute name="Datum" type="xs:date" use="required"/>
        <xs:attribute name="Bevetel" type="xs:decimal" use="required"/>
        <xs:attribute name="DID" type="xs:int" use="required"/>
        <xs:attribute name="VID" type="xs:int" use="required"/>
    </xs:complexType>

    <!-- Kiszállítás -->
    <xs:complexType name="KiszallitasType">
        <xs:attribute name="Ker-e" type="xs:boolean" use="required"/>
        <xs:attribute name="SzallitasiAr" type="xs:decimal" use="optional"/>
    </xs:complexType>

    <!-- Dolgozók -->
    <!-- A Dolgozók gyűjtő elemének típusa -->
    <xs:complexType name="DolgozokType">
        <xs:sequence>
            <xs:element name="Dolgozo" type="DolgozoType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Egy Dolgozó elemet leíró típus -->
    <xs:complexType name="DolgozoType">
        <xs:attribute name="DID" type="xs:int" use="required"/>
        <xs:attribute name="Nev" type="xs:string" use="required"/>
        <xs:attribute name="TelSzam" type="xs:string" use="required"/>
        <xs:attribute name="Elerheto" type="xs:boolean" use="required"/>
    </xs:complexType>

    <!-- Vásárlók -->
    <!-- A Vásárlók gyűjtő elemének típusa -->
    <xs:complexType name="VasarlokType">
        <xs:sequence>
            <xs:element name="Vasarlo" type="VasarloType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Egy Vásárló elemet leíró típus -->
    <xs:complexType name="VasarloType">
        <xs:sequence>
            <xs:element name="Lakcim" type="LakcimType"/>
        </xs:sequence>
        <xs:attribute name="VID" type="xs:int" use="required"/>
        <xs:attribute name="Nev" type="xs:string" use="required"/>
        <xs:attribute name="SzuletesiIdo" type="xs:date" use="required"/>
        <xs:attribute name="VTelSzam" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Lakcím -->
    <xs:complexType name="LakcimType">
        <xs:sequence>
            <xs:element name="Iranyitoszam" type="xs:int"/>
            <xs:element name="Telepules" type="xs:string"/>
            <xs:element name="UtcaesHazszam" type="xs:string"/>
            <xs:element name="Emelet" type="xs:int" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== regecz/CNGDZ3WebXML/CNGDZ3_feleves_feladat/DOMParseCNGDZ3/XMLCNGDZ3_modified.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><Adatbazis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaCNGDZ3.xsd">
    <!-- Típusok -->
    <Tipusok>
        <Tipus TNev="Bútor" TipKod="1"/>
        <Tipus TNev="Elektromos eszköz" TipKod="2"/>
        <Tipus TNev="Konyhai felszerelés" TipKod="3"/>
    </Tipusok>

    <!-- Termékek -->
    <Termekek>
        <Termek TerKod="101" TerNev="Szék" TermekAr="5000" TipKod="1"/>
        <Termek TerKod="102" TerNev="Asztal" TermekAr="15000" TipKod="1"/>
        <Termek TerKod="201" TerNev="Hűtő" TermekAr="80000" TipKod="2"/>
        <Termek TerKod="202" TerNev="Sütő" TermekAr="45000" TipKod="3"/>
        <Termek TerKod="203" TerNev="Fazék" TermekAr="12000" TipKod="3"/>
    </Termekek>

    <!-- Rendelések -->
    <Rendelesek>
        <Rendeles Bevetel="25000" DID="1" Datum="2024-01-15" RSzam="R001" VID="1001">
            <Kiszallitas Ker-e="true" SzallitasiAr="1500"/>
        </Rendeles>
        <Rendeles Bevetel="5000" DID="2" Datum="2024-01-20" RSzam="R002" VID="1002">
            <Kiszallitas Ker-e="false"/>
        </Rendeles>
        <Rendeles Bevetel="12500" DID="3" Datum="2024-01-25" RSzam="R003" VID="1003">
            <Kiszallitas Ker-e="true" SzallitasiAr="2000"/>
        </Rendeles>
    </Rendelesek>

    <!-- Dolgozók -->
    <Dolgozok>
        <Dolgozo DID="1" Elerheto="true" Nev="Kovács Béla" TelSzam="+36123456789"/>
        <Dolgozo DID="2" Elerheto="false" Nev="Nagy Anna" TelSzam="+36198765432"/>
        <Dolgozo DID="3" Elerheto="true" Nev="Szabó Péter" TelSzam="+36201234567"/>
    </Dolgozok>

    <!-- Vásárlók -->
    <Vasarlok>
        <Vasarlo Nev="Szabó János" SzuletesiIdo="1980-05-15" VID="1001" VTelSzam="+36201234567">
            <Lakcim>
                <Iranyitoszam>1011</Iranyitoszam>
                <Telepules>Budapest</Telepules>
                <UtcaesHazszam>Fő utca 10</UtcaesHazszam>
                <Emelet>2</Emelet>
            </Lakcim>
        </Vasarlo>
        <Vasarlo Nev="Kiss Éva" SzuletesiIdo="1992-03-22" VID="1002" VTelSzam="+36207654321">
            <Lakcim>
                <Iranyitoszam>6720</Iranyitoszam>
                <Telepules>Szeged</Telepules>
                <UtcaesHazszam>Kossuth utca 5</UtcaesHazszam>
                <Emelet>1</Emelet>
            </Lakcim>
        </Vasarlo>
        <Vasarlo Nev="Tóth Gábor" SzuletesiIdo="1985-08-30" VID="1003" VTelSzam="+36203456789">
            <Lakcim>
                <Iranyitoszam>8200</Iranyitoszam>
                <Telepules>Veszprém</Telepules>
                <UtcaesHazszam>Petőfi utca 12</UtcaesHazszam>
                <Emelet>3</Emelet>
            </Lakcim>
        </Vasarlo>
    </Vasarlok>
</Adatbazis>
